version: '3.8'

services:
  # 1. Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: hospital-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 210805
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis — fila de mensagens para o worker
  redis:
    image: redis:7-alpine
    container_name: hospital-redis
    restart: always
    ports:
      - "6379:6379"

  # 3. Backend (Spring Boot)
  backend:
    build:
      context: ./Sistema/demo
      dockerfile: Dockerfile
    container_name: hospital-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hospital_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=210805
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - REDIS_HOST=redis

  # 4. Frontend (React/Vite)
  frontend:
    build:
      context: "./Front Sistema/recepcao-hospital"
      dockerfile: Dockerfile
    container_name: hospital-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: