-- V1__schema_inicial.sql
-- Criação das tabelas base do sistema hospitalar
-- Esta migration representa o estado inicial gerado pelo Hibernate

CREATE TABLE IF NOT EXISTS paciente (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(255) NOT NULL,
    cpf                VARCHAR(255) NOT NULL,
    data_nascimento    VARCHAR(255),
    genero             VARCHAR(255),
    telefone           VARCHAR(255),
    nome_mae           VARCHAR(255),
    nome_pai           VARCHAR(255),
    numero_sus         VARCHAR(15),
    possui_convenio    BOOLEAN NOT NULL DEFAULT FALSE,
    numero_convenio    VARCHAR(255),
    cep                VARCHAR(255),
    rua                VARCHAR(255),
    bairro             VARCHAR(255),
    cidade             VARCHAR(255),
    uf                 VARCHAR(255),
    peso               VARCHAR(255),
    altura             VARCHAR(255),
    CONSTRAINT UKfvlo8m5kqpr7knbyw4rjyer2s UNIQUE (cpf)
);

CREATE TABLE IF NOT EXISTS consulta (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               BIGINT,
    senha                 VARCHAR(255),
    status                VARCHAR(255) CHECK (status IN ('AGUARDANDO','EM_ATENDIMENTO','CONCLUIDO')),
    prioridade            VARCHAR(255),
    consultorio           VARCHAR(255),
    data_hora             TIMESTAMP(6),
    data_hora_conclusao   TIMESTAMP(6),
    observacoes           TEXT,
    paciente_id           BIGINT,
    CONSTRAINT FK1oq22nlbbvpijm5n2t6vqi1is FOREIGN KEY (paciente_id) REFERENCES paciente(id)
);

CREATE TABLE IF NOT EXISTS funcionario (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                   VARCHAR(255) NOT NULL,
    cargo                  VARCHAR(255) NOT NULL,
    cpf                    VARCHAR(255),
    data_nascimento        VARCHAR(255),
    registro_profissional  VARCHAR(255),
    senha                  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS log_atendimento (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_evento          VARCHAR(255),
    descricao            TEXT,
    usuario_responsavel  VARCHAR(255),
    data_hora            TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS pre_agendamento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(255),
    cpf              VARCHAR(255),
    telefone         VARCHAR(255),
    data_nascimento  VARCHAR(255),
    sintomas         TEXT,
    status           VARCHAR(255) CHECK (status IN ('PENDENTE','AGUARDANDO_NOME','AGUARDANDO_CPF','AGUARDANDO_SINTOMAS','CONCLUIDO')),
    data_solicitacao TIMESTAMP(6)
);